stages:
  - build
  - deploy
  - reload

webpack:
  stage: build
  image: node:latest
  script:
    - npm install
    - npm run lint
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 day

deploy:mainsimweb:
  stage: deploy
  tags:
    - mainsimweb
    - httpd
  dependencies:
    - webpack
  script:
    - rsync -arv --delete dist/ /var/www/html

deploy:docker-mainsimweb:
  stage: deploy
  tags:
    - mainsimweb-docker
  script:
    - wget https://github.com/docker/compose/releases/download/1.23.2/run.sh -O /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose
    - cd daemons/mainsimweb
    - docker-compose up

deploy:mainsim:
  stage: deploy
  tags:
    - mainsim
    - httpd
  dependencies:
    - webpack
  script:
    - rsync -av --delete dist/ /var/www/html

reload:
  stage: reload
  image: mainsim.etit.tu-chemnitz.de:5555/images/mqtt_publish:latest
  script:
    - mosquitto_pub -h mainsimweb.etit.tu-chemnitz.de -u "mqtt" -P "$MQTT_PASSWORD" -q 0 -t "frontend/update" -m ''
