stages:
  - build
  - deploy

image: node:latest

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 day

deploy:mainsimweb:
  stage: deploy
  tags:
    - mainsimweb
    - httpd
  script:
    - rsync -arv --delete dist/ /var/www/html

deploy:mainsim:
  stage: deploy
  tags:
    - mainsim
    - httpd
  script:
    - rsync -arv --delete dist/ /var/www/html
