stages:
  - build
  - deploy
  - reload

webpack:
  stage: build
  image: node:latest
  script:
    - npm install
    - npm run lint
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 day

deploy:docker-mainsimweb:
  stage: deploy
  tags:
    - mainsimweb-docker
  dependencies: []
  script:
    - apk add py-pip
    - pip install docker-compose
    - cd daemons/mainsimweb
    - docker-compose up -d

deploy:mainsimweb:
  stage: deploy
  tags:
    - mainsimweb
    - httpd
  dependencies:
    - webpack
  script:
    - rsync -arv --delete dist/ /var/www/html

deploy:mainsim:
  stage: deploy
  tags:
    - mainsim
    - httpd
  dependencies:
    - webpack
  script:
    - rsync -av --delete dist/ /var/www/html
