stages:
  - build
  - deploy

image: node:latest

build:
  stage: build
  tags:
    - docker
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/
    expire_in: 1 day
