stages:
  - build
  - deploy
  - reload

webpack:
  stage: build
  image: node:latest
  script:
    - npm install
    - npm run lint
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 day

docker-build:
  stage: build
  image: docker:stable
  tags:
    - mainsimweb
    - docker-build
  script:
    - docker build -t mainsimstatus-cache cache-daemon

deploy:mainsimweb:
  stage: deploy
  tags:
    - mainsimweb
    - httpd
  dependencies:
    - webpack
  script:
    - rsync -arv --delete dist/ /var/www/html

deploy:mainsim:
  stage: deploy
  tags:
    - mainsim
    - httpd
  dependencies:
    - webpack
  script:
    - rsync -arv --delete dist/ /var/www/html

docker-deploy-mainsimweb:
  stage: deploy
  tags:
    - mainsimweb
    - docker-build
  script:
    - docker images
    - docker ps -a

reload:
  stage: reload
  image: ubuntu:latest
  script:
    - apt update
    - apt install mosquitto-clients -y
    - mosquitto_pub -h mainsimweb.etit.tu-chemnitz.de -u "mqtt" -P "$MQTT_PASSWORD" -q 0 -t "frontend/update" -m ''
