stages:
  - build
  - deploy

image: alpine:latest

build:dev:
  stage: build
  only:
    - develop
    - /^feature-.*$/
  script:
    - apk update
    - apk add nodejs nodejs-npm git
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/
    expire_in: 1 month
