stages:
  - build
  - deploy

webpack:
  stage: build
  image: node:latest
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 day

docker-build:
  stage: build
  image: docker:stable
  tags:
    - mainsimweb
    - docker-build
  script:
    - docker info
    - docker build -t mainsimweb-cache cache-daemon

deploy:mainsimweb:
  stage: deploy
  tags:
    - mainsimweb
    - httpd
  dependencies:
    - webpack
  script:
    - rsync -arv --delete dist/ /var/www/html

deploy:mainsim:
  stage: deploy
  tags:
    - mainsim
    - httpd
  dependencies:
    - webpack
  script:
    - rsync -arv --delete dist/ /var/www/html
