stages:
  - build
  - deploy
  - reload

webpack:
  stage: build
  image: node:latest
  script:
    - npm install
    - npm run lint
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 day

docker-build:
  stage: build
  image: docker:stable
  tags:
    - docker-build
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE/cache-daemon daemons/cache-daemon
    - docker push $CI_REGISTRY_IMAGE/cache-daemon

deploy:mainsimweb:
  stage: deploy
  tags:
    - mainsimweb
    - httpd
  dependencies:
    - webpack
  script:
    - rsync -arv --delete dist/ /var/www/html

deploy:mainsim:
  stage: deploy
  tags:
    - mainsim
    - httpd
  dependencies:
    - webpack
  script:
    - rsync -arv --delete dist/ /var/www/html

reload:
  stage: reload
  image: mainsim.etit.tu-chemnitz.de:5555/images/mqtt_publish:latest
  script:
    - mosquitto_pub -h mainsimweb.etit.tu-chemnitz.de -u "mqtt" -P "$MQTT_PASSWORD" -q 0 -t "frontend/update" -m ''
