version: "3"
services:
  auth:
    build: auth
    image: mainsim.etit.tu-chemnitz.de:5555/simadmin/mainsimstatus/auth
    volumes:
      - authsecrets:/secrets
    environment:
      SECRETS_FILE: /secrets/auth_secret.txt
    ports:
      - 127.0.0.1:1881:8000
    restart: always
  cache:
    build: cache
    image: mainsim.etit.tu-chemnitz.de:5555/simadmin/mainsimstatus/cache
    ports:
      - 127.0.0.1:1880:8080
    restart: always
  mensa:
    build: mensa
    image: mainsim.etit.tu-chemnitz.de:5555/simadmin/mainsimstatus/mensa
    ports:
      - 127.0.0.1:1885:8000
    restart: always

volumes:
  authsecrets:

