version: "3"
services: 
  auth:
    build: auth
    ports:
     - 127.0.0.1:1881:8000
    restart: always
  cache:
    build: cache
    ports:
     - 127.0.0.1:1880:8080
    restart: always
  mqtt:
    build: mqtt
    ports:
     - 1883:1883
     - 8883:8883
     - 9001:9001
    restart: always
